import { ways } from "@/data";
import Button from "@/shared/ui/Button";
import Cart_btn from "@/shared/ui/Cart_btn";
import Filtr from "@/shared/ui/Filtr";
import Footer from "@/shared/ui/Footer";
import Header from "@/shared/ui/Header";
import WayToTeach from "@/shared/ui/WayToTeach";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";


export default function Home() {
const [filterOpen, setFilterOpen] = useState(false)
const [requEst, setRequestOpen] = useState(false)
const [help, setOpenHelp] = useState(false)
const [gp, setOpenGp] = useState(false)
  



  return (
    <>
      <Head>
        <title>Поиск мест по интересам</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
           <section>
            <div className="container">
             <Header/>
             <div className="banner">
             <div className="banner_top">
               <div className="banner_left">
                <h1>
                Социальная <br />
                 интерактивная  <br />
                <span className="txtg">платформа</span>
              </h1>
              
              <p className="txt2">
                Соединяем <span className="txtg">гостей и места</span> <br />
                Общение, бронирование <span  className="txtg">здесь и сейчас</span>
              </p>
              </div>
               
               <div className="banner_rigth">
                 <img src="./img/bnr_rigth.png" alt="" />
               </div>
             </div>


             <div className="banner_bottom">
               <Filtr/>

               <div className="dv" onClick={() => setFilterOpen(!filterOpen)}>
                <input type="text" placeholder="Введите название площадки" className="flltr_gi"/>
               </div>

               <div className={`flltr_bl ${filterOpen ? "actv" : ""}`}>
                <p className="txt6">Фильтрация поиска</p>


                <div className="clse" onClick={() => setFilterOpen(false)}>
                    <img src="./img/cls.png" alt="" />
                  </div>


                  <div className="np_block">
                    
                    <div className="np_itmq">
                      <p className="txt7">Тип площадки</p>
                      <select className="sl"  name="" id="">
                        <option value="Выберите варианты">Выберите варианты</option>
                      </select>
                    </div>

                     <div className="np_itmq">
                      <p className="txt7">Особенности</p>
                      <select className="sl"  name="" id="">
                        <option value="Выберите варианты">Выберите варианты</option>
                      </select>
                    </div>

                    <div className="np_itmq">
                      <p className="txt7">Вместимость</p>
                      <select className="sl"  name="" id="">
                        <option value="Выберите варианты">Выберите варианты</option>
                      </select>
                    </div>
                  </div>
               </div>


               <div className="btn_block">
               <Cart_btn/>

              <button className="btn2">
                <Link href="/List" className="lnk4">
                Показать списком
                </Link>
              </button>
               </div>

             </div>
             </div>

            </div>
           </section>

           <section>
            <div className="container">
              <div className="category_block">
                 <p className="txt4">
                  Места <span className="txtg">
                    по категориям
                  </span>
                 </p>
                
                <div className="category_grid">
                 <div className="caregory_itm">
                   <p className="txt5">
                    Отдых
                   </p>

                   <div className="ct_left">
                     <div className="mg">
                      <img src="./img/ctr_itm.png" alt="" />
                     </div>
                   </div>
                 </div>
                    
                    <div className="caregory_itm">
                   <p className="txt5">
                    Бизнес
                   </p>

                   <div className="ct_left">
                     <div className="mg">
                      <img src="./img/rack.png" alt="" />
                     </div>
                   </div>
                 </div>

                 <div className="caregory_itm">
                   <p className="txt5">
                    Банкеты
                   </p>

                   <div className="ct_left">
                     <div className="mg">
                      <img src="./img/banquets.png" alt="" />
                     </div>
                   </div>
                 </div>

                 <div className="caregory_itm">
                   <p className="txt5">
                    Здоровье
                   </p>

                   <div className="ct_left">
                     <div className="mg">
                      <img src="./img/health.png" alt="" />
                     </div>
                   </div>
                 </div>
                </div>
              </div>

            </div>
           </section>

           <section>
            <div className="container">
               <div className="last_added_block">
                  <p className="txt14">
                  последние <span className="txtg2">
                    добавленные
                  </span>
                 </p>

                  <div className="last_added_grid">
                    <div className="last_itm">
                     <div className="last_top">
                      <img src="./img/lst_top.png" alt="" />

                      <div className="favorite_itm">
                        <img src="./img/fvrt.png" alt="" />
                      </div>
                     </div>

                      <div className="last_bottom">
                        <p className="txt8">
                          Банкетный зал лофт <br />
                           Форест Холл
                        </p>

                        <div className="str_block">
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>

                          <p className="txt9">
                            (23)
                          </p>
                        </div>
                        
                        <div className="lst_txt">
                          <div className="ty">
                            <div className="lctn">
                              <img src="./img/location.png" alt="" />
                            </div>
                            <p className="txt10">
                            Сокольники
                          </p>
                          </div>


                          <p className="txt11">5 мин пешком</p>
                        </div>


                        <div className="lst_hmm">
                          <div className="usrgi">
                            <img src="./img/Users.png" alt="" />
                          </div>

                          <p className="txt12">35/100/150</p>
                        </div>
                          
                          <div className="lst_txt_btn">
                            <div className="money_block">
                            <div className="wlt">
                              <img src="./img/Wallet.png" alt="" />
                            </div>

                             <p className="txt13">$$$</p>
                            </div>


                            <button className="btn3">
                              <Link href="#" className="lnk5">
                              Подробнее
                              </Link>
                            </button>
                          </div>

                      </div>
                    </div>


                    <div className="last_itm">
                     <div className="last_top">
                      <img src="./img/lst_top.png" alt="" />

                      <div className="favorite_itm">
                        <img src="./img/fvrt.png" alt="" />
                      </div>
                     </div>

                      <div className="last_bottom">
                        <p className="txt8">
                          Ресторан Londri у метро <br />
                          Лубянка
                        </p>

                        <div className="str_block">
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>

                          <p className="txt9">
                            (23)
                          </p>
                        </div>
                        
                        <div className="lst_txt">
                          <div className="ty">
                            <div className="lctn">
                              <img src="./img/location.png" alt="" />
                            </div>
                            <p className="txt10">
                            Сокольники
                          </p>
                          </div>


                          <p className="txt11">5 мин пешком</p>
                        </div>


                        <div className="lst_hmm">
                          <div className="usrgi">
                            <img src="./img/Users.png" alt="" />
                          </div>

                          <p className="txt12">35/100/150</p>
                        </div>
                          
                          <div className="lst_txt_btn">
                            <div className="money_block">
                            <div className="wlt">
                              <img src="./img/Wallet.png" alt="" />
                            </div>

                             <p className="txt13">$$$</p>
                            </div>


                            <button className="btn3">
                              <Link href="#" className="lnk5">
                              Подробнее
                              </Link>
                            </button>
                          </div>

                      </div>
                    </div>


                    <div className="last_itm">
                     <div className="last_top">
                      <img src="./img/lst_top.png" alt="" />
                      
                      <div className="favorite_itm">
                        <img src="./img/fvrt.png" alt="" />
                      </div>
                     </div>

                      <div className="last_bottom">
                        <p className="txt8">
                          Ресторан Londri у метро <br />
                          Лубянка
                        </p>

                        <div className="str_block">
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>

                          <p className="txt9">
                            (23)
                          </p>
                        </div>
                        
                        <div className="lst_txt">
                          <div className="ty">
                            <div className="lctn">
                              <img src="./img/location.png" alt="" />
                            </div>
                            <p className="txt10">
                            Сокольники
                          </p>
                          </div>


                          <p className="txt11">5 мин пешком</p>
                        </div>


                        <div className="lst_hmm">
                          <div className="usrgi">
                            <img src="./img/Users.png" alt="" />
                          </div>

                          <p className="txt12">35/100/150</p>
                        </div>
                          
                          <div className="lst_txt_btn">
                            <div className="money_block">
                            <div className="wlt">
                              <img src="./img/Wallet.png" alt="" />
                            </div>

                             <p className="txt13">$$$</p>
                            </div>


                            <button className="btn3">
                              <Link href="#" className="lnk5">
                              Подробнее
                              </Link>
                            </button>
                          </div>

                      </div>
                    </div>


                    <div className="last_itm">
                     <div className="last_top">
                      <img src="./img/lst_top.png" alt="" />
                      
                      <div className="favorite_itm">
                        <img src="./img/fvrt.png" alt="" />
                      </div>
                     </div>

                      <div className="last_bottom">
                        <p className="txt8">
                          Ресторан Londri у метро <br />
                          Лубянка
                        </p>

                        <div className="str_block">
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>

                          <p className="txt9">
                            (23)
                          </p>
                        </div>
                        
                        <div className="lst_txt">
                          <div className="ty">
                            <div className="lctn">
                              <img src="./img/location.png" alt="" />
                            </div>
                            <p className="txt10">
                            Сокольники
                          </p>
                          </div>


                          <p className="txt11">5 мин пешком</p>
                        </div>


                        <div className="lst_hmm">
                          <div className="usrgi">
                            <img src="./img/Users.png" alt="" />
                          </div>

                          <p className="txt12">35/100/150</p>
                        </div>
                          
                          <div className="lst_txt_btn">
                            <div className="money_block">
                            <div className="wlt">
                              <img src="./img/Wallet.png" alt="" />
                            </div>

                             <p className="txt13">$$$</p>
                            </div>


                            <button className="btn3">
                              <Link href="#" className="lnk5">
                              Подробнее
                              </Link>
                            </button>
                          </div>

                      </div>
                    </div>
                  </div>
                   
                  <div className="btn_cntrr">
                    <button className="btn4">
                     Показать еще 18
                   </button>
                  </div>

               </div>
            </div>
           </section>

           <section>
            <div className="container">
              <div className="container">
               <div className="last_added_block">
                  <p className="txt14">
                  Самые <span className="txtg2">
                    популярные
                  </span>
                 </p>

                  <div className="last_added_grid">
                    <div className="last_itm">
                     <div className="last_top">
                      <img src="./img/lst_top.png" alt="" />

                      <div className="favorite_itm">
                        <img src="./img/fvrt.png" alt="" />
                      </div>
                     </div>

                      <div className="last_bottom">
                        <p className="txt8">
                          Банкетный зал лофт <br />
                           Форест Холл
                        </p>

                        <div className="str_block">
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>

                          <p className="txt9">
                            (23)
                          </p>
                        </div>
                        
                        <div className="lst_txt">
                          <div className="ty">
                            <div className="lctn">
                              <img src="./img/location.png" alt="" />
                            </div>
                            <p className="txt10">
                            Сокольники
                          </p>
                          </div>


                          <p className="txt11">5 мин пешком</p>
                        </div>


                        <div className="lst_hmm">
                          <div className="usrgi">
                            <img src="./img/Users.png" alt="" />
                          </div>

                          <p className="txt12">35/100/150</p>
                        </div>
                          
                          <div className="lst_txt_btn">
                            <div className="money_block">
                            <div className="wlt">
                              <img src="./img/Wallet.png" alt="" />
                            </div>

                             <p className="txt13">$$$</p>
                            </div>


                            <button className="btn3">
                              <Link href="#" className="lnk5">
                              Подробнее
                              </Link>
                            </button>
                          </div>

                      </div>
                    </div>


                    <div className="last_itm">
                     <div className="last_top">
                      <img src="./img/lst_top.png" alt="" />

                      <div className="favorite_itm">
                        <img src="./img/fvrt.png" alt="" />
                      </div>
                     </div>

                      <div className="last_bottom">
                        <p className="txt8">
                          Ресторан Londri у метро <br />
                          Лубянка
                        </p>

                        <div className="str_block">
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>

                          <p className="txt9">
                            (23)
                          </p>
                        </div>
                        
                        <div className="lst_txt">
                          <div className="ty">
                            <div className="lctn">
                              <img src="./img/location.png" alt="" />
                            </div>
                            <p className="txt10">
                            Сокольники
                          </p>
                          </div>


                          <p className="txt11">5 мин пешком</p>
                        </div>


                        <div className="lst_hmm">
                          <div className="usrgi">
                            <img src="./img/Users.png" alt="" />
                          </div>

                          <p className="txt12">35/100/150</p>
                        </div>
                          
                          <div className="lst_txt_btn">
                            <div className="money_block">
                            <div className="wlt">
                              <img src="./img/Wallet.png" alt="" />
                            </div>

                             <p className="txt13">$$$</p>
                            </div>


                            <button className="btn3">
                              <Link href="#" className="lnk5">
                              Подробнее
                              </Link>
                            </button>
                          </div>

                      </div>
                    </div>


                    <div className="last_itm">
                     <div className="last_top">
                      <img src="./img/lst_top.png" alt="" />
                      
                      <div className="favorite_itm">
                        <img src="./img/fvrt.png" alt="" />
                      </div>
                     </div>

                      <div className="last_bottom">
                        <p className="txt8">
                          Ресторан Londri у метро <br />
                          Лубянка
                        </p>

                        <div className="str_block">
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>

                          <p className="txt9">
                            (23)
                          </p>
                        </div>
                        
                        <div className="lst_txt">
                          <div className="ty">
                            <div className="lctn">
                              <img src="./img/location.png" alt="" />
                            </div>
                            <p className="txt10">
                            Сокольники
                          </p>
                          </div>


                          <p className="txt11">5 мин пешком</p>
                        </div>


                        <div className="lst_hmm">
                          <div className="usrgi">
                            <img src="./img/Users.png" alt="" />
                          </div>

                          <p className="txt12">35/100/150</p>
                        </div>
                          
                          <div className="lst_txt_btn">
                            <div className="money_block">
                            <div className="wlt">
                              <img src="./img/Wallet.png" alt="" />
                            </div>

                             <p className="txt13">$$$</p>
                            </div>


                            <button className="btn3">
                              <Link href="#" className="lnk5">
                              Подробнее
                              </Link>
                            </button>
                          </div>

                      </div>
                    </div>


                    <div className="last_itm">
                     <div className="last_top">
                      <img src="./img/lst_top.png" alt="" />
                      
                      <div className="favorite_itm">
                        <img src="./img/fvrt.png" alt="" />
                      </div>
                     </div>

                      <div className="last_bottom">
                        <p className="txt8">
                          Ресторан Londri у метро <br />
                          Лубянка
                        </p>

                        <div className="str_block">
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>

                          <p className="txt9">
                            (23)
                          </p>
                        </div>
                        
                        <div className="lst_txt">
                          <div className="ty">
                            <div className="lctn">
                              <img src="./img/location.png" alt="" />
                            </div>
                            <p className="txt10">
                            Сокольники
                          </p>
                          </div>


                          <p className="txt11">5 мин пешком</p>
                        </div>


                        <div className="lst_hmm">
                          <div className="usrgi">
                            <img src="./img/Users.png" alt="" />
                          </div>

                          <p className="txt12">35/100/150</p>
                        </div>
                          
                          <div className="lst_txt_btn">
                            <div className="money_block">
                            <div className="wlt">
                              <img src="./img/Wallet.png" alt="" />
                            </div>

                             <p className="txt13">$$$</p>
                            </div>


                            <button className="btn3">
                              <Link href="#" className="lnk5">
                              Подробнее
                              </Link>
                            </button>
                          </div>

                      </div>
                    </div>
                  </div>
                   
                  <div className="btn_cntrr">
                    <button className="btn4">
                     Показать еще 8
                   </button>
                  </div>

               </div>
            </div>
            </div>
           </section>

           <section>
            <div className="container">
              <div className="block_v">
                <p className="txt15">
                  Варианты взаимодействия с <span className="txtg2">GP Platform</span>
                </p>
                 
                 <div className={`request_modal ${requEst ? "active_v" : ""}`}>
                    <div className="request_top">

                      <div className="clls" onClick={() => setRequestOpen(false)}>
                      <img src="./img/cls.png" alt="закрыть" />
                    </div>

                   <p className="txt19">
                    Форма для размещения запроса
                   </p>
                    </div>


                 </div>

                <div className="block_v_frid">
                 <div className="v_itm">
                  <p className="txt16">
                    1
                  </p>

                  <div className="v_left">
                    <p className="txt17">
                      Самостоятельный поиск и бронирование
                    </p>

                    <p className="txt18">
                      С помощью удобного фильтра и карты подбираете  <br />
                       места и сами связываетесь с ними через чат, запрос <br />
                       или звоните. Данную опцию можно использовать без  <br />
                        на платформе (за исключением чата).
                    </p>

                    <button className="btn5 btq">
                      <Link href="#" className="lnk6">
                      Каталог поиска
                      </Link>
                    </button>
                  </div>

                 </div>


                  <div className="v_itm">
                  <p className="txt16">
                    2
                  </p>

                  <div className="v_left">
                    <p className="txt17">
                      Возможность разместить запрос
                    </p>

                    <p className="txt18">
                      Запрос увидят площадки подходящие по  <br />
                      параметрам, указанным вами при заполнении формы.  <br />
                      Они сами свяжутся с вами в удобное время, отправят   <br />
                       предложение в чат личного кабинета...  <Link href="#" className="lnk7">подробнее</Link>
                    </p>

                    <button className="btn6 btq" onClick={() => setRequestOpen(!requEst)}>
                       Разместить запрос
                    </button>
                  </div>

                 </div>

                 <div className={`gp_modal ${gp ? "actv_2" : ""}`}>
                   <div className="cls_tp">
                    <button className="close3" onClick={() => setOpenGp(false)}>
                    <img src="./list_img/cls.png" alt="close" />
                   </button>
                  
                   <p className="txt26">
                       помощь <span className="b_txt">эксперта</span>
                   </p>

                    <form action="#">
                      
                    <div className="gp_input_bl">
                        <input type="text" placeholder="Ваше имя" className="gp_input"/>
                      <input type="tel" placeholder="Ваш номер телефона" className="gp_input"/>
                      <input type="tel" placeholder="Удобное время для звонка" className="gp_input"/>

                      <div className="dt_block">
                      <input type="date" name="Дата" id="" className="date_itm"/>

                      <div className="counter_2">
                        <p className="txt27">Кол-во гостей</p>
                      </div>
                    </div>
                      
                      <input type="text" placeholder="Ваше сообщение (необязательно)" className="gp_input"/>
                        
                        <button className="btn10">
                          Отправить
                        </button>
                    </div>
                    </form>
                   </div>
                 </div> 

                 <div className="v_itm">
                  <p className="txt16">
                    3
                  </p>

                  <div className="v_left">
                    <p className="txt17">
                      Помощь эксперта GP
                    </p>

                    <p className="txt18">
                      Запрос увидят площадки подходящие по  <br />
                      параметрам, указанным вами при заполнении формы.  <br />
                      Они сами свяжутся с вами в удобное время, отправят   <br />
                       предложение в чат личного кабинета...  <Link href="#" className="lnk7">подробнее</Link>
                    </p>

                    <button className="btn7 btq" onClick={() => setOpenGp(!gp)}>
                       Получить помощь
                    </button>
                  </div>

                 </div>

                  <div className={`help_modal ${help ? "ctv" : ""}`}>
                   <div className="help_top">
                     <div className="close2" onClick={() => setOpenHelp(false)}>
                    <img src="./img/cls.png" alt="закрыть" />
                   </div>

                     
                   </div>

                    <p className="txt21">
                      Нужна помощь?
                    </p>

                    <p className="txt22">
                      Воспользуйтесь услугой по подбору от GP!  <br />
                      Стоимость услуги — 1000 р. 
                    </p>

                    <form action="#">
                      <div className="inp_block">
                      <input type="text" className="inpq" placeholder="Ваше имя"/>
                      <input type="tel" className="inpq" placeholder="Ваш номер телефона"/>
                      <input type="text" className="inpq" placeholder="Ваш комментарий (необязательно)"/>

                      <select name="" id="" className="slct">
                        <option value="Выберите вариант">Выберите вариант</option>
                      </select>


                      <div className="in_block">
                        <input type="date" name="" id="" className="date"/>
                      

                        <div className="counter">
                          <p className="txt23">Кол-во гостей</p>
                        </div>
                      </div>

                    </div>
                     

                    </form>

                    <button className="btn9">
                       <Link href="#" className="lnk8">
                       Перейти к оплате
                       </Link>
                     </button>
                  </div>
                     
                 <div className="v_itm">
                  <p className="txt16">
                    4
                  </p>

                  <div className="v_left">
                    <p className="txt17">
                      Дополнительный сервис от GP
                    </p>

                    <p className="txt18">
                      Запрос увидят площадки подходящие по  <br />
                      параметрам, указанным вами при заполнении формы.  <br />
                      Они сами свяжутся с вами в удобное время, отправят   <br />
                       предложение в чат личного кабинета...  <Link href="#" className="lnk7">подробнее</Link>
                    </p>

                    <button className="btn8 btq" onClick={() => setOpenHelp(!help)}>
                       Заказать услугу
                    </button>
                  </div>

                 </div>
                </div>

              </div>
            </div>
           </section>

            <section>
              <div className="container">
                <div className="gp_block">
                 <div className="gp_itm">
                   <p className="txt24">
                     Для быстрого поиска Вы можете пользоваться <br />
                     всеми вариантами <span className="txtg2">одновременно</span>.
                   </p>

                   <p className="txt25">
                   <span className="txtg2">GP Платформа</span> позволяет общаться напрямую здесь и сейчас. <br />
                   Мы за «прозрачные отношения»
                   </p>

                 </div>
                </div>  

              </div>
            </section>

            <section>
              <div className="container">
                <div className="ul_b">
                   <ul className="ul3">
                      <WayToTeach description={ways[0].description}/>

                      <WayToTeach {...ways[1]}/>
                      <WayToTeach {...ways[2]}/>
                   </ul>
                </div>

              </div>
            </section>

            <section>
              <div className="container">
               <div className="btn_block_q">
                <Button>Подход</Button>
                <Button>Доступность</Button>
                <Button>Концентрация</Button>
               </div>
              </div>
            </section>

            <section>
              <div className="container">
                <Footer/>
              </div>
            </section>
            
        </main>
      </div>
    </>
  );
}
