import { ways } from "@/data";
import Button from "@/shared/ui/Button";
import Cart_btn from "@/shared/ui/Cart_btn";
import Filtr from "@/shared/ui/Filtr";
import Footer from "@/shared/ui/Footer";
import Header from "@/shared/ui/Header";
import Reservations from "@/shared/ui/Reservations";
import WayToTeach from "@/shared/ui/WayToTeach";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";


export default function Home() {
const [filterOpen, setFilterOpen] = useState(false)
const [requEst, setRequestOpen] = useState(false)
const [help, setOpenHelp] = useState(false)
const [gp, setOpenGp] = useState(false)


console.log("App component render");
let content = "нажми на кнопку"
  
function handleClick(type){
  console.log("button clicked", type);
  content = type
}


  return (
    <>
      <Head>
        <title>Поиск мест по интересам</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
           <section>
            <div className="container">
             <Header/>
             <div className="banner">
             <div className="banner_top">
               <div className="banner_left">
                <h1>
                Социальная <br />
                 интерактивная  <br />
                <span className="txtg">платформа</span>
              </h1>
              
              <p className="txt2">
                Соединяем <span className="txtg">гостей и места</span> <br />
                Общение, бронирование <span  className="txtg">здесь и сейчас</span>
              </p>
              </div>
               
               <div className="banner_rigth">
                 <img src="./img/bnr_rigth.png" alt="" />
               </div>
             </div>


             <div className="banner_bottom">
               <Filtr/>

               <div className="dv" onClick={() => setFilterOpen(!filterOpen)}>
                <input type="text" placeholder="Введите название площадки" className="flltr_gi"/>
               </div>

               <div className={`flltr_bl ${filterOpen ? "actv" : ""}`}>
                <p className="txt6">Фильтрация поиска</p>


                <div className="clse" onClick={() => setFilterOpen(false)}>
                    <img src="./img/cls.png" alt="" />
                  </div>


                  <div className="np_block">
                    
                    <div className="np_itmq">
                      <p className="txt7">Тип площадки</p>
                      <select className="sl"  name="" id="">
                        <option value="Выберите варианты">Выберите варианты</option>
                      </select>
                    </div>

                     <div className="np_itmq">
                      <p className="txt7">Особенности</p>
                      <select className="sl"  name="" id="">
                        <option value="Выберите варианты">Выберите варианты</option>
                      </select>
                    </div>

                    <div className="np_itmq">
                      <p className="txt7">Вместимость</p>
                      <select className="sl"  name="" id="">
                        <option value="Выберите варианты">Выберите варианты</option>
                      </select>
                    </div>
                  </div>
               </div>


               <div className="btn_block">
               <Cart_btn/>

              <button className="btn2">
                <Link href="/List" className="lnk4">
                Показать списком
                </Link>
              </button>
               </div>

             </div>
             </div>

            </div>
           </section>

           <section>
            <div className="container">
              <div className="category_block">
                 <p className="txt4">
                  Места <span className="txtg">
                    по категориям
                  </span>
                 </p>
                
                <div className="category_grid">
                 <div className="caregory_itm">
                   <p className="txt5">
                    Отдых
                   </p>

                   <div className="ct_left">
                     <div className="mg">
                      <img src="./img/ctr_itm.png" alt="" />
                     </div>
                   </div>
                 </div>
                    
                    <div className="caregory_itm">
                   <p className="txt5">
                    Бизнес
                   </p>

                   <div className="ct_left">
                     <div className="mg">
                      <img src="./img/rack.png" alt="" />
                     </div>
                   </div>
                 </div>

                 <div className="caregory_itm">
                   <p className="txt5">
                    Банкеты
                   </p>

                   <div className="ct_left">
                     <div className="mg">
                      <img src="./img/banquets.png" alt="" />
                     </div>
                   </div>
                 </div>

                 <div className="caregory_itm">
                   <p className="txt5">
                    Здоровье
                   </p>

                   <div className="ct_left">
                     <div className="mg">
                      <img src="./img/health.png" alt="" />
                     </div>
                   </div>
                 </div>
                </div>
              </div>

            </div>
           </section>

           <section>
            <div className="container">
               <div className="last_added_block">
                  <p className="txt14">
                  последние <span className="txtg2">
                    добавленные
                  </span>
                 </p>

                  <div className="last_added_grid">
                    <div className="last_itm">
                     <div className="last_top">
                      <img src="./img/lst_top.png" alt="" />

                      <div className="favorite_itm">
                        <img src="./img/fvrt.png" alt="" />
                      </div>
                     </div>

                      <div className="last_bottom">
                        <p className="txt8">
                          Банкетный зал лофт <br />
                           Форест Холл
                        </p>

                        <div className="str_block">
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>

                          <p className="txt9">
                            (23)
                          </p>
                        </div>
                        
                        <div className="lst_txt">
                          <div className="ty">
                            <div className="lctn">
                              <img src="./img/location.png" alt="" />
                            </div>
                            <p className="txt10">
                            Сокольники
                          </p>
                          </div>


                          <p className="txt11">5 мин пешком</p>
                        </div>


                        <div className="lst_hmm">
                          <div className="usrgi">
                            <img src="./img/Users.png" alt="" />
                          </div>

                          <p className="txt12">35/100/150</p>
                        </div>
                          
                          <div className="lst_txt_btn">
                            <div className="money_block">
                            <div className="wlt">
                              <img src="./img/Wallet.png" alt="" />
                            </div>

                             <p className="txt13">$$$</p>
                            </div>


                            <button className="btn3">
                              <Link href="/Product" className="lnk5">
                              Подробнее
                              </Link>
                            </button>
                          </div>

                      </div>
                    </div>


                    <div className="last_itm">
                     <div className="last_top">
                      <img src="./img/lst_top.png" alt="" />

                      <div className="favorite_itm">
                        <img src="./img/fvrt.png" alt="" />
                      </div>
                     </div>

                      <div className="last_bottom">
                        <p className="txt8">
                          Ресторан Londri у метро <br />
                          Лубянка
                        </p>

                        <div className="str_block">
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>

                          <p className="txt9">
                            (23)
                          </p>
                        </div>
                        
                        <div className="lst_txt">
                          <div className="ty">
                            <div className="lctn">
                              <img src="./img/location.png" alt="" />
                            </div>
                            <p className="txt10">
                            Сокольники
                          </p>
                          </div>


                          <p className="txt11">5 мин пешком</p>
                        </div>


                        <div className="lst_hmm">
                          <div className="usrgi">
                            <img src="./img/Users.png" alt="" />
                          </div>

                          <p className="txt12">35/100/150</p>
                        </div>
                          
                          <div className="lst_txt_btn">
                            <div className="money_block">
                            <div className="wlt">
                              <img src="./img/Wallet.png" alt="" />
                            </div>

                             <p className="txt13">$$$</p>
                            </div>


                            <button className="btn3">
                              <Link href="/Product" className="lnk5">
                              Подробнее
                              </Link>
                            </button>
                          </div>

                      </div>
                    </div>


                    <div className="last_itm">
                     <div className="last_top">
                      <img src="./img/lst_top.png" alt="" />
                      
                      <div className="favorite_itm">
                        <img src="./img/fvrt.png" alt="" />
                      </div>
                     </div>

                      <div className="last_bottom">
                        <p className="txt8">
                          Ресторан Londri у метро <br />
                          Лубянка
                        </p>

                        <div className="str_block">
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>

                          <p className="txt9">
                            (23)
                          </p>
                        </div>
                        
                        <div className="lst_txt">
                          <div className="ty">
                            <div className="lctn">
                              <img src="./img/location.png" alt="" />
                            </div>
                            <p className="txt10">
                            Сокольники
                          </p>
                          </div>


                          <p className="txt11">5 мин пешком</p>
                        </div>


                        <div className="lst_hmm">
                          <div className="usrgi">
                            <img src="./img/Users.png" alt="" />
                          </div>

                          <p className="txt12">35/100/150</p>
                        </div>
                          
                          <div className="lst_txt_btn">
                            <div className="money_block">
                            <div className="wlt">
                              <img src="./img/Wallet.png" alt="" />
                            </div>

                             <p className="txt13">$$$</p>
                            </div>


                            <button className="btn3">
                              <Link href="/Product" className="lnk5">
                              Подробнее
                              </Link>
                            </button>
                          </div>

                      </div>
                    </div>


                    <div className="last_itm">
                     <div className="last_top">
                      <img src="./img/lst_top.png" alt="" />
                      
                      <div className="favorite_itm">
                        <img src="./img/fvrt.png" alt="" />
                      </div>
                     </div>

                      <div className="last_bottom">
                        <p className="txt8">
                          Ресторан Londri у метро <br />
                          Лубянка
                        </p>

                        <div className="str_block">
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>

                          <p className="txt9">
                            (23)
                          </p>
                        </div>
                        
                        <div className="lst_txt">
                          <div className="ty">
                            <div className="lctn">
                              <img src="./img/location.png" alt="" />
                            </div>
                            <p className="txt10">
                            Сокольники
                          </p>
                          </div>


                          <p className="txt11">5 мин пешком</p>
                        </div>


                        <div className="lst_hmm">
                          <div className="usrgi">
                            <img src="./img/Users.png" alt="" />
                          </div>

                          <p className="txt12">35/100/150</p>
                        </div>
                          
                          <div className="lst_txt_btn">
                            <div className="money_block">
                            <div className="wlt">
                              <img src="./img/Wallet.png" alt="" />
                            </div>

                             <p className="txt13">$$$</p>
                            </div>


                            <button className="btn3">
                              <Link href="/Product" className="lnk5">
                              Подробнее
                              </Link>
                            </button>
                          </div>

                      </div>
                    </div>
                  </div>
                   
                  <div className="btn_cntrr">
                    <button className="btn4">
                     Показать еще 18
                   </button>
                  </div>

               </div>
            </div>
           </section>

           <section>
            <div className="container">
              <div className="container">
               <div className="last_added_block">
                  <p className="txt14">
                  Самые <span className="txtg2">
                    популярные
                  </span>
                 </p>

                  <div className="last_added_grid">
                    <div className="last_itm">
                     <div className="last_top">
                      <img src="./img/lst_top.png" alt="" />

                      <div className="favorite_itm">
                        <img src="./img/fvrt.png" alt="" />
                      </div>
                     </div>

                      <div className="last_bottom">
                        <p className="txt8">
                          Банкетный зал лофт <br />
                           Форест Холл
                        </p>

                        <div className="str_block">
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>

                          <p className="txt9">
                            (23)
                          </p>
                        </div>
                        
                        <div className="lst_txt">
                          <div className="ty">
                            <div className="lctn">
                              <img src="./img/location.png" alt="" />
                            </div>
                            <p className="txt10">
                            Сокольники
                          </p>
                          </div>


                          <p className="txt11">5 мин пешком</p>
                        </div>


                        <div className="lst_hmm">
                          <div className="usrgi">
                            <img src="./img/Users.png" alt="" />
                          </div>

                          <p className="txt12">35/100/150</p>
                        </div>
                          
                          <div className="lst_txt_btn">
                            <div className="money_block">
                            <div className="wlt">
                              <img src="./img/Wallet.png" alt="" />
                            </div>

                             <p className="txt13">$$$</p>
                            </div>


                            <button className="btn3">
                              <Link href="#" className="lnk5">
                              Подробнее
                              </Link>
                            </button>
                          </div>

                      </div>
                    </div>


                    <div className="last_itm">
                     <div className="last_top">
                      <img src="./img/lst_top.png" alt="" />

                      <div className="favorite_itm">
                        <img src="./img/fvrt.png" alt="" />
                      </div>
                     </div>

                      <div className="last_bottom">
                        <p className="txt8">
                          Ресторан Londri у метро <br />
                          Лубянка
                        </p>

                        <div className="str_block">
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>

                          <p className="txt9">
                            (23)
                          </p>
                        </div>
                        
                        <div className="lst_txt">
                          <div className="ty">
                            <div className="lctn">
                              <img src="./img/location.png" alt="" />
                            </div>
                            <p className="txt10">
                            Сокольники
                          </p>
                          </div>


                          <p className="txt11">5 мин пешком</p>
                        </div>


                        <div className="lst_hmm">
                          <div className="usrgi">
                            <img src="./img/Users.png" alt="" />
                          </div>

                          <p className="txt12">35/100/150</p>
                        </div>
                          
                          <div className="lst_txt_btn">
                            <div className="money_block">
                            <div className="wlt">
                              <img src="./img/Wallet.png" alt="" />
                            </div>

                             <p className="txt13">$$$</p>
                            </div>


                            <button className="btn3">
                              <Link href="#" className="lnk5">
                              Подробнее
                              </Link>
                            </button>
                          </div>

                      </div>
                    </div>


                    <div className="last_itm">
                     <div className="last_top">
                      <img src="./img/lst_top.png" alt="" />
                      
                      <div className="favorite_itm">
                        <img src="./img/fvrt.png" alt="" />
                      </div>
                     </div>

                      <div className="last_bottom">
                        <p className="txt8">
                          Ресторан Londri у метро <br />
                          Лубянка
                        </p>

                        <div className="str_block">
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>

                          <p className="txt9">
                            (23)
                          </p>
                        </div>
                        
                        <div className="lst_txt">
                          <div className="ty">
                            <div className="lctn">
                              <img src="./img/location.png" alt="" />
                            </div>
                            <p className="txt10">
                            Сокольники
                          </p>
                          </div>


                          <p className="txt11">5 мин пешком</p>
                        </div>


                        <div className="lst_hmm">
                          <div className="usrgi">
                            <img src="./img/Users.png" alt="" />
                          </div>

                          <p className="txt12">35/100/150</p>
                        </div>
                          
                          <div className="lst_txt_btn">
                            <div className="money_block">
                            <div className="wlt">
                              <img src="./img/Wallet.png" alt="" />
                            </div>

                             <p className="txt13">$$$</p>
                            </div>


                            <button className="btn3">
                              <Link href="#" className="lnk5">
                              Подробнее
                              </Link>
                            </button>
                          </div>

                      </div>
                    </div>


                    <div className="last_itm">
                     <div className="last_top">
                      <img src="./img/lst_top.png" alt="" />
                      
                      <div className="favorite_itm">
                        <img src="./img/fvrt.png" alt="" />
                      </div>
                     </div>

                      <div className="last_bottom">
                        <p className="txt8">
                          Ресторан Londri у метро <br />
                          Лубянка
                        </p>

                        <div className="str_block">
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>
                          <div className="str">
                            <img src="./img/star.png" alt="" />
                          </div>

                          <p className="txt9">
                            (23)
                          </p>
                        </div>
                        
                        <div className="lst_txt">
                          <div className="ty">
                            <div className="lctn">
                              <img src="./img/location.png" alt="" />
                            </div>
                            <p className="txt10">
                            Сокольники
                          </p>
                          </div>


                          <p className="txt11">5 мин пешком</p>
                        </div>


                        <div className="lst_hmm">
                          <div className="usrgi">
                            <img src="./img/Users.png" alt="" />
                          </div>

                          <p className="txt12">35/100/150</p>
                        </div>
                          
                          <div className="lst_txt_btn">
                            <div className="money_block">
                            <div className="wlt">
                              <img src="./img/Wallet.png" alt="" />
                            </div>

                             <p className="txt13">$$$</p>
                            </div>


                            <button className="btn3">
                              <Link href="#" className="lnk5">
                              Подробнее
                              </Link>
                            </button>
                          </div>

                      </div>
                    </div>
                  </div>
                   
                  <div className="btn_cntrr">
                    <button className="btn4">
                     Показать еще 8
                   </button>
                  </div>

               </div>
            </div>
            </div>
           </section>

           <section>
            <div className="container">
              <Reservations/>
            </div>
           </section>

            <section>
              <div className="container">
                <div className="gp_block">
                 <div className="gp_itm">
                   <p className="txt24">
                     Для быстрого поиска Вы можете пользоваться <br />
                     всеми вариантами <span className="txtg2">одновременно</span>.
                   </p>

                   <p className="txt25">
                   <span className="txtg2">GP Платформа</span> позволяет общаться напрямую здесь и сейчас. <br />
                   Мы за «прозрачные отношения»
                   </p>

                 </div>
                </div>  

              </div>
            </section>

            <section>
              <div className="container">
                <div className="ul_b">
                   <ul className="ul3">
                      <WayToTeach description={ways[0].description}/>

                      <WayToTeach {...ways[1]}/>
                      <WayToTeach {...ways[2]}/>
                   </ul>
                </div>

              </div>
            </section>

            <section>
              <div className="container">
               <div className="btn_block_q">
                <Button onClick={() => handleClick()}>Подход</Button>
                <Button onClick={() => handleClick()}>Доступность</Button>
                <Button onClick={() => handleClick()}>Концентрация</Button>

                <p>{content}</p>
               </div>
              </div>
            </section>

            <section>
              <div className="container">
                
              </div>
            </section>

            <section>
              <div className="container">
                <Footer/>
              </div>
            </section>
            
        </main>
      </div>
    </>
  );
}
